name: Gatsby Publish

on: push

jobs:
  publish:
    name: publish to github pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          DEPLOY-BRANCH: main
          ACCESS-TOKEN: ${{ secrets.ACCESS_TOKEN }}

    